spring.application.name=QuadLingo
spring.datasource.url=jdbc:postgresql://localhost:5432/quad
spring.datasource.username=postgres
spring.datasource.password=zxccxz7705
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect